//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angel_lab1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotasEstudiante
    {
        public string Nombre { get; set; }
        public Nullable<double> Laboratorio_1 { get; set; }
        public Nullable<double> Laboratorio_2 { get; set; }
        public Nullable<double> Laboratorio_3 { get; set; }
        public Nullable<double> Parcial_1 { get; set; }
        public Nullable<double> Parcial_2 { get; set; }
        public Nullable<double> Parcial_3 { get; set; }
    }
}
